### ISSUE TITLE
Trouble when exception happen in the last callback (done)

### ISSUE THREAD

**Issue by micky2be** [Wizcorp/event-wrapper#1]
When there is an exception thrown in the callback it generate the execution of the event to fail and call `done` see [Line 30](https://github.com/Wizcorp/event-wrapper/blob/master/index.js#L30);

Since the function is already been executed (or in the middle of it) it throws an error on [Line 10](https://github.com/Wizcorp/event-wrapper/blob/master/index.js#L10). _Cannot read property `length` of null"_

``` js
var wrap = createEventWrapper(myEmitter, function (error) {
    throw new Error('boom!');
});

wrap('lastEvent', function (msg) {
    wrap.done();
});
```

It makes it really problematic for debugging.

**Comment by ronkorving** [comment]
Fix landed in https://github.com/Wizcorp/event-wrapper/commit/6ee4ab2db5e9826bc1b9aed941fdc46a3b3bc74f
